---
- name: Get latest version
  shell: >
    curl -s https://api.github.com/repos/monochromegane/the_platinum_searcher/releases/latest | grep browser_download_url |  grep 'linux_amd64[.]tar[.]gz' | head -n 1 | cut -d '"' -f 4
  register: pt_latest_archive_url

- name: Download archive
  get_url: url={{ pt_latest_archive_url.stdout }} dest=/tmp/pt_linux_amd64.tar.gz

- name: Extract archive
  unarchive: src=/tmp/pt_linux_amd64.tar.gz dest=/tmp copy=no

- name: Install binary
  copy: src=/tmp/pt_linux_amd64/pt dest=/usr/local/bin/pt mode=0755 owner=root group=root
